ValidaDVAgenciaDVConta/Models/ContaBancaria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ValidaDVAgenciaDVConta.Models
{
    public class ContaBancaria
    {
        public string Banco { get; set; }
        public string Agencia { get; set; }

        public int DvAgencia { get; set; }
        public string Conta { get; set; }
        public int DvConta { get; set; }
    }
}

ValidaDVAgenciaDVConta/Models/ErrorViewModel.cs
using System;

namespace ValidaDVAgenciaDVConta.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ValidaDVAgenciaDVConta/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ValidaDVAgenciaDVConta.Models;

namespace ValidaDVAgenciaDVConta.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ValidaDVAgenciaDVConta/Controllers/ValidaAgenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ValidaDVAgenciaDVConta.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace ValidaDVAgenciaDVConta.Controllers
{
    public class ValidaAgenciaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GerarDV(ContaBancaria contaBancaria)
        {
            if (ModelState.IsValid)
            {
                ValidarDvAgenciaConta(contaBancaria);
            }
            return View(contaBancaria);
        }

        private void ValidarDvAgenciaConta(ContaBancaria conta)
        {
            switch (conta.Banco)
            {
                case "104":
                    {

                        break;
                    }
                case "001":
                    {
                        ValidarBancoBrasil(conta);
                        break;
                    }
                case "033":
                    {
                        ValidarSantander(conta);
                        break;
                    }
                case "341":
                    {
                        ValidarItau(conta);
                        break;
                    }
            }
        }

        private void ValidarSantander(ContaBancaria conta)
        {
            try
            {
                if (conta.Agencia.Length > 4)
                {
                    throw new Exception("Agencia inválida.");
                }

                if (conta.Conta.Length > 8)
                {
                    throw new Exception("Conta inválida.");
                }
                List<int> pesoConta = new List<int>() { 9, 7, 3, 1, 0, 0, 9, 7, 1, 3, 1, 9, 7, 3 };

                var agenciaConta = string.Concat(conta.Agencia, "00", conta.Conta);

                List<int> algarismosAgenciaConta = new List<int>();

                for (int i = 0; i < agenciaConta.Length; i++)
                {
                    algarismosAgenciaConta.Add(Convert.ToInt32(agenciaConta[i].ToString()));
                }

                int soma = 0;

                for (int i = 0; i < pesoConta.Count(); i++)
                {
                    int num = algarismosAgenciaConta[i] * (pesoConta[i]);

                    soma += num;
                }

                if (soma > 9)
                {
                    soma = soma % 10;
                }

                int digitoCalculado = 10 - soma;

                if (conta.DvConta != digitoCalculado)
                {
                    throw new Exception("Digito da conta é invalido.");
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        private void ValidarItau(ContaBancaria conta)
        {
            try
            {
                if (conta.Agencia.Length > 4)
                {
                    throw new Exception("Agencia inválida.");
                }

                if (conta.Conta.Length > 5)
                {
                    throw new Exception("Conta inválida.");
                }

                List<int> pesoConta = new List<int>() { 2, 1, 2, 1, 2, 1, 2, 1, 2 };

                var agenciaConta = string.Concat(conta.Agencia, conta.Conta);

                List<int> algarismosAgenciaConta = new List<int>();

                for (int i = 0; i < agenciaConta.Length; i++)
                {
                    algarismosAgenciaConta.Add(Convert.ToInt32(agenciaConta[i].ToString()));
                }

                int soma = 0;

                for (int i = 0; i < pesoConta.Count(); i++)
                {
                    int num = algarismosAgenciaConta[i] * (pesoConta[i]);

                    if (num > 9)
                    {
                        int aux = num;
                        List<int> algarismosnum = new List<int>();
                        while (aux > 0)
                        {
                            algarismosnum.Add(aux % 10);
                            aux = aux / 10;
                        }

                        num = algarismosnum.Sum();
                    }

                    soma += num;
                }
                int digitocalc = 10 - (soma % 10);

                if (conta.DvConta != (digitocalc))
                {
                    throw new Exception("Digito da conta é invalido.");
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        private void ValidarBancoBrasil(ContaBancaria conta)
        {
            try
            {
                if (conta.Agencia.Length > 4)
                {
                    throw new Exception("Agencia inválida.");
                }

                if (conta.Conta.Length > 8)
                {
                    throw new Exception("Conta inválida.");
                }

                List<int> algarismoAgencia = new List<int>();
                for (int i = 0; i < conta.Agencia.Length; i++)
                {
                    algarismoAgencia.Add(Convert.ToInt32(conta.Agencia[i].ToString()));
                }

                int soma = 0;
                int pesoAgencia = 5;

                foreach (var algarismo in algarismoAgencia)
                {
                    soma += algarismo * (pesoAgencia);
                    pesoAgencia--;
                }

                conta.DvAgencia = 11 - (soma % 11);

                soma = 0;
                int pesoConta = 9;

                List<int> algarismosConta = new List<int>();
                for (int i = 0; i < conta.Conta.Length; i++)
                {
                    algarismosConta.Add(Convert.ToInt32(conta.Conta[i].ToString()));
                }


                foreach (var algarismo in algarismosConta)
                {
                    soma += algarismo * (pesoConta);
                    pesoConta--;
                }

                var digitoconta = 11 - (soma % 11);

                if (digitoconta != Convert.ToInt32(conta.DvConta))
                {
                    throw new Exception("Digito da conta é invalido.");
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

ValidaDVAgenciaDVConta/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ValidaDVAgenciaDVConta/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ValidaDVAgenciaDVConta/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ValidaDVAgenciaDVConta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ValidaDVAgenciaDVConta</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ValidaDVAgenciaDVConta</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ValidaDVAgenciaDVConta</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ValidaDVAgenciaDVConta/Views/ValidaAgencia/GerarDV.cshtml
@model ContaBancaria
@{
    ViewData["Title"] = "GerarDV";
}

<h2>GerarDV</h2>

<div class="row">
    <div class="form-group col-sm-2">
        <label for="Banco">Banco</label>
        <input class="form-control" type="text" asp-for="Banco"  />
    </div>
    <div class="form-group col-sm-2">
        <label for="Agencia">Agencia</label>
        <input class="form-control" type="text" asp-for="Agencia" />
    </div>
    <div class="form-group col-sm-1">
        <label for="DvAgencia">DV</label>
        <input class="form-control" type="text" asp-for="DvAgencia" />
    </div>
    <div class="form-group col-sm-2">
        <label for="txtConta">Conta</label>
        <input class="form-control" type="text" asp-for="Conta"  />
    </div>
    <div class="form-group col-sm-1">
        <label for="txtDvConta">DV</label>
        <input class="form-control" type="text" asp-for="DvConta"/>
    </div>
</div>

ValidaDVAgenciaDVConta/Views/ValidaAgencia/Index.cshtml
@model ValidaDVAgenciaDVConta.Models.ContaBancaria
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<form asp-antiforgery="true" asp-action="GerarDV" asp-controller="ValidaAgencia" method="post">
    <fieldset>
        <div class="row">
            <div class="form-group col-sm-2">
                <label for="txtBanco">Banco</label>
                <input type="text" asp-for="Banco" class="form-control" />
            </div>
            <div class="form-group col-sm-2">
                <label for="Agencia">Agencia</label>
                <input type="text" asp-for="Agencia" class="form-control" />
            </div>
            <div class="form-group col-sm-2">
                <label for="txtConta">Conta</label>
                @Html.EditorFor(model => model.Conta, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group col-sm-1">
                <label for="txtDvConta">DV</label>
                @Html.EditorFor(model => model.DvConta, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div>
            @*@Html.ActionLink("Validar","GerarDV","ValidaAgencia",null,new { htmlAttributes = new { @class="btn btn-primary"} })*@
            <button type="submit" class="btn btn-primary">Validar</button>
        </div>
    </fieldset>
</form>